### ISSUE TITLE
Linkify

### ISSUE THREAD

**Issue by zayaisshawn** [andrewcoelho/react-text-editor#1]
Hi, do you use this in any production apps?. If so, do you have a plan to add link functionality? Also it'd nice to include the styles for the demo.

**Comment by andrewcoelho** [comment]
This is not currently being used in production. I created this project simply to get to know Draft.js better. I updated the repo with an example folder that includes the stylesheet (which is terrible currently). 

I hope to clear up some time to clean this up a bit and add more functionality (such as automatic link decorating) as I will need to integrate this into another project I'm working on soon.
