### ISSUE TITLE
Upload Image has error

### ISSUE THREAD

**Issue by DerekHung** [andrewcoelho/react-text-editor#2]
Hello andrewcoelho 
I tried to run your example( from github ), but when I choose the image to upload
I met this error:   

nullthrows.js:18   Uncaught Error: Got unexpected null or undefined

file loader is working fine, there seems like some problem in insertImage.js
and I found your another place example is working fine when I upload image => http://www.andrewcoelho.com/react-text-editor/

thank you~

**Comment by andrewcoelho** [comment]
Hi Derek,

After a quick look, I'm not sure what is causing that.

This is by no means a production ready text editor. I built it mainly to experiment with the Draft.js library and only spent a couple hours cobbling it together. There are no tests, a lot of the code is tightly coupled, and a lot of questionable assumptions were made.

That said, I have now reached a point in a different, much larger production project I'm working on that will require a production ready version of this text editor. I plan to start working on that in 2.5 weeks. 

This repo will probably be rewritten from the ground up, with the same focus on creating an experience similar to Facebook Notes or Medium that can be dropped into whatever application you're building.

Sorry I couldn't help but thanks for the heads up!

**Comment by DerekHung** [comment]
But your code here http://www.andrewcoelho.com/react-text-editor/ is working fine

or could you put your http://www.andrewcoelho.com/react-text-editor/ resource on another branch? I would try to find out what problem to cause this error happened.

**Comment by andrewcoelho** [comment]
Yeah, unfortunately the code running on that example is from before I changed the structure of the repo to even allow an example to be run. So the only thing you would be able to see is the bundle powering it by going to the gh-pages branch of this repo and looking in the public/js/ folder there.

**Comment by DerekHung** [comment]
hello,
I fix this problem by adding AtomicBlockUtils.insertAtomicBlock
And I make a pull request for it~

**Comment by andrewcoelho** [comment]
I'm glad newer versions of Draft.js make this easier to do. It will make my job easier when I get back into it. Thanks for your PR!
